# Generates web_assets.cpp from the files in WEB_DIR. Invoked by add_custom_command (cmake -P).
# Each entry: <request path>|<file>|<content type>
set(ODEUM_WEB_ENTRIES
  "/join|join.html|text/html"
  "/overlay|overlay.html|text/html"
  "/web/odeum.css|odeum.css|text/css"
  "/web/effects.js|effects.js|text/javascript"
  "/web/socket.js|socket.js|text/javascript"
  "/web/join.js|join.js|text/javascript"
  "/web/overlay.js|overlay.js|text/javascript")

set(body "// Generated by embed_web.cmake. Do not edit.\n#include \"web_assets.hpp\"\n#include <array>\n\nnamespace odeum::relay {\nnamespace {\n")
set(table "")
set(index 0)
foreach(entry IN LISTS ODEUM_WEB_ENTRIES)
  string(REPLACE "|" ";" parts "${entry}")
  list(GET parts 0 route)
  list(GET parts 1 file)
  list(GET parts 2 type)
  file(READ "${WEB_DIR}/${file}" hex HEX)
  string(LENGTH "${hex}" hex_length)
  math(EXPR size "${hex_length} / 2")
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
  string(APPEND body "const unsigned char asset_${index}[] = {${bytes}0};\n")
  string(APPEND table "    {\"${route}\", {\"${type}; charset=utf-8\", std::string_view(reinterpret_cast<const char*>(asset_${index}), ${size})}},\n")
  math(EXPR index "${index} + 1")
endforeach()
string(APPEND body "struct Route { std::string_view path; WebAsset asset; };\nconst std::array<Route, ${index}> routes{{\n${table}}};\n}\n")
string(APPEND body "const WebAsset* find_web_asset(std::string_view path) {\n    for (const auto& route : routes) if (route.path == path) return &route.asset;\n    return nullptr;\n}\n}\n")
file(WRITE "${OUTPUT}.tmp" "${body}")
file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.tmp")
